name: Codesign Product
description: Submit product to notary

inputs:
  sign:
    required: true
    type: string
  keychain:
    required: true
    type: string
  apple_id:
    required: true
    type: string 
  team_id:
    required: true
    type: string 
  password:
    required: true
    type: string 
  product_path:
    required: true
    type: string
  dmg_path:
    required: true
    type: string

outputs:
  product_path: 
    value: ${{ inputs.product_path }}
  dmg_path: 
    value: ${{ inputs.dmg_path }}
  notarization_status:
    value: ${{ steps.notarytool.outputs.notarization_status }}

runs:
  using: "composite"
  steps:

    - name: setup
      id: setup
      run: |
        echo "dmg_path=${{ inputs.dmg_path }}" >> $GITHUB_OUTPUT
        curl "${entitlements_url}" -o entitlements.plist -sL
        echo "entitlements_path=${GITHUB_WORKSPACE}/entitlements.plist" >> $GITHUB_OUTPUT
      shell: bash
      env:
        path: ${{ inputs.product_path }}
        entitlements_url: 'https://raw.githubusercontent.com/miyako/4D/v1/entitlements.plist'

    - name: Export codesign variables
      shell: bash
      run: |
        export sign="${{ inputs.sign }}"
        export keychain="${{ inputs.keychain }}"
        export entitlements_path="${{ steps.setup.outputs.entitlements_path }}"
        echo "✅ Variables codesign exportées pour toutes les boucles"
        
    - name: Codesign
      shell: bash
      run: |
        set -euo pipefail

        retry_codesign() {
          local target="$1"
          local timestamp_flag="$2"
          local attempt=1
          local max_attempts=5
          local delay=5

          while [ $attempt -le $max_attempts ]; do
            echo "[$attempt/$max_attempts] codesign de: $target"

            output=$(codesign --verbose --deep --strict --options=runtime $timestamp_flag \
              --force --sign "$sign" --keychain "$keychain" \
              --entitlements "$entitlements_path" "$target" 2>&1)
            status=$?
            echo "$output"

            if [ $status -eq 0 ]; then
              echo "✅ codesign réussi pour $target"
              return 0
            fi

            if echo "$output" | grep -qiE "no identity found|password|resource fork|invalid|not found in keychain|code object is not signed at all"; then
              echo "❌ Erreur fatale détectée, arrêt immédiat."
              return 1
            fi

            echo "⚠️ Tentative $attempt échouée, nouvelle tentative dans ${delay}s..."
            attempt=$(( attempt + 1 ))
            sleep $delay
            delay=$(( delay * 2 ))
          done

          echo "❌ Échec après $max_attempts tentatives pour $target"
          return 1
        }

        IFS=$'\n'; set -f

        echo "🔹 Collecting binaries, frameworks, bundles, apps, 4dbase/4darchive..."

        # --- Binaires externes ---
        find "${{ inputs.product_path }}" -type f \( -perm -111 -o -name "*.dylib" -o -name "*.so" \) \
          ! -path "*.4dbase/*" ! -path "*.4darchive/*" \
          | while IFS= read -r f; do
              retry_codesign "$f" "--timestamp" || exit 1
            done

        # --- Frameworks ---
        find "${{ inputs.product_path }}" -type d -name "*.framework" \
          | while IFS= read -r f; do
              retry_codesign "$f" "--timestamp" || exit 1
            done

        # --- Bundles, plugins, kexts ---
        find "${{ inputs.product_path }}" -type d \( -name "*.bundle" -o -name "*.plugin" -o -name "*.kext" \) \
          | while IFS= read -r f; do
              retry_codesign "$f" "--timestamp" || exit 1
            done

        # --- .4dbase et .4darchive ---
        find "${{ inputs.product_path }}" -type d \( -name "*.4dbase" -o -name "*.4darchive" \) \
          | while IFS= read -r bundle; do
              find "$bundle" -type f \( -perm -111 -o -name "*.dylib" -o -name "*.so" \) \
                | while IFS= read -r f; do
                    retry_codesign "$f" "--timestamp" || exit 1
                  done
            done

        # --- Apps internes ---
        find "${{ inputs.product_path }}" -type d -name "*.app" \
          | while IFS= read -r f; do
              retry_codesign "$f" "--timestamp" || exit 1
            done

        # --- App racine (si .app) ---
        if [[ "${{ inputs.product_path }}" == *.app ]]; then
          retry_codesign "${{ inputs.product_path }}" "--timestamp" || exit 1
        fi

        echo "✅ Tous les composants ont été signés et vérifiés correctement."

    - name: Create DMG
      id: hdiutil
      shell: bash
      env:
        product_path: ${{ inputs.product_path }}
        dmg_path: ${{ steps.setup.outputs.dmg_path }}
      run: |
        set -euo pipefail
        SRC="${product_path}"
        OUT="${dmg_path}"
        VOLNAME="$(basename "${OUT%.dmg}")"
        WORKDIR="$(mktemp -d /tmp/dmgbuild.XXXXXX)"
        MOUNT_DIR="${WORKDIR}/mnt"
        mkdir -p "$MOUNT_DIR"

        echo "[i] Creating sparse image..."
        SRC_MB=$(( $(du -sm "$SRC" | cut -f1) ))
        NEEDED_MB=$(( SRC_MB * 2 ))
        hdiutil create -type SPARSE -fs HFS+ -volname "$VOLNAME" -size "${NEEDED_MB}m" -nospotlight -ov "${WORKDIR}/staging.sparseimage"
        hdiutil attach "${WORKDIR}/staging.sparseimage" -nobrowse -noverify -noautoopen -owners on -mountpoint "$MOUNT_DIR"
        rsync -a "$SRC/" "$MOUNT_DIR/"
        sync
        hdiutil detach "$MOUNT_DIR"
        hdiutil convert "${WORKDIR}/staging.sparseimage" -format UDBZ -o "$OUT" -ov
        echo "[✓] DMG ready: $OUT"

    - name: Notarize with Apple NotaryTool
      shell: bash
      run: |
        echo "📦 Soumission à Apple NotaryTool..."
        xcrun notarytool submit "${{ inputs.dmg_path }}" \
          --apple-id "${{ inputs.apple_id }}" \
          --team-id "${{ inputs.team_id }}" \
          --password "${{ inputs.password }}" \
          --wait \
          --output-format json > notarytool-output.json

        status=$(jq -r '.status // empty' notarytool-output.json)
        submission_id=$(jq -r '.id // empty' notarytool-output.json)
        echo "🛡️ Statut notarisation: $status"

        if [[ "$status" == "Accepted" ]]; then
          echo "✅ Notarisation réussie"
          exit 0
        elif [[ "$status" == "Invalid" ]]; then
          echo "❌ Notarisation rejetée"
          xcrun notarytool log "$submission_id" \
            --apple-id "${{ inputs.apple_id }}" \
            --team-id "${{ inputs.team_id }}" \
            --password "${{ inputs.password }}" \
            --output-format normal || true
          exit 1
        else
          echo "❌ Statut inattendu: $status"
          exit 1
        fi