name: Codesign Product
description: Submit product to notary

inputs:
  sign:
    required: true
    type: string
  keychain:
    required: true
    type: string
  apple_id:
    required: true
    type: string 
  team_id:
    required: true
    type: string 
  password:
    required: true
    type: string 
  product_path:
    required: true
    type: string
  dmg_path:
    required: true
    type: string

outputs:
  product_path: 
    value: ${{ inputs.product_path }}
  dmg_path: 
    value: ${{ inputs.dmg_path }}
  notarization_status:
    value: ${{ steps.notarytool.outputs.notarization_status }}

runs:
  using: "composite"
  steps:

    - name: setup
      id: setup
      run: |
        echo "dmg_path=${{ inputs.dmg_path }}" >> $GITHUB_OUTPUT
        curl "${entitlements_url}" -o entitlements.plist -sL
        echo "entitlements_path=${GITHUB_WORKSPACE}/entitlements.plist" >> $GITHUB_OUTPUT
      shell: bash
      env:
        path: ${{ inputs.product_path }}
        entitlements_url: 'https://raw.githubusercontent.com/miyako/4D/v1/entitlements.plist'

    - name: Export codesign variables
      shell: bash
      run: |
        export sign="${{ inputs.sign }}"
        export keychain="${{ inputs.keychain }}"
        export entitlements_path="${{ steps.setup.outputs.entitlements_path }}"
        echo "✅ Variables codesign exportées pour toutes les boucles"
        
    - name: Codesign
      shell: bash
      run: |
        set -euo pipefail
        export sign="${sign}"
        export keychain="${keychain}"
        export entitlements_path="${entitlements_path}"
        export product_path="${product_path}"

        retry_codesign() {
          local target="$1"
          local attempt=1
          local max_attempts=2
          local delay=5
          while [ $attempt -le $max_attempts ]; do
            echo "[$attempt/$max_attempts] codesign de: $target"
            if codesign --verbose --deep --strict --options=runtime --timestamp \
              --force --sign "${sign}" --keychain "${keychain}" --entitlements "${entitlements_path}" "$target"; then
              echo "✅ codesign réussi pour $target"
              return 0
            fi
            echo "⚠️ Tentative $attempt échouée, nouvelle tentative dans ${delay}s..."
            sleep $delay
            attempt=$(( attempt + 1 ))
            delay=$(( delay * 2 ))
          done
          echo "❌ Échec après $max_attempts tentatives pour $target"
          return 1
        }

        # Signer tous les bundles / apps / 4dbase / 4darchive
        while IFS= read -r -d '' item; do
          retry_codesign "$item" || exit 1
        done < <(find "${product_path}" -type d \( -name "*.app" -o -name "*.4dbase" -o -name "*.4darchive" \) -print0)

        # Signer frameworks / plugins / bundles / kext
        while IFS= read -r -d '' item; do
          retry_codesign "$item" || exit 1
        done < <(find "${product_path}" -type d \( -name "*.framework" -o -name "*.bundle" -o -name "*.plugin" -o -name "*.kext" \) -print0)

        # Signature finale de la racine si .app
        if [[ "${product_path}" == *.app ]]; then
          retry_codesign "$product_path" || exit 1
        fi

        echo "✅ Tous les composants signés (batch) et vérifiés."

    - name: Create DMG
      id: hdiutil
      shell: bash
      env:
        product_path: ${{ inputs.product_path }}
        dmg_path: ${{ steps.setup.outputs.dmg_path }}
      run: |
        set -euo pipefail
        SRC="${product_path}"
        OUT="${dmg_path}"
        VOLNAME="$(basename "${OUT%.dmg}")"
        WORKDIR="$(mktemp -d /tmp/dmgbuild.XXXXXX)"
        MOUNT_DIR="${WORKDIR}/mnt"
        mkdir -p "$MOUNT_DIR"

        echo "[i] Creating sparse image..."
        SRC_MB=$(( $(du -sm "$SRC" | cut -f1) ))
        NEEDED_MB=$(( SRC_MB * 2 ))
        hdiutil create -type SPARSE -fs HFS+ -volname "$VOLNAME" -size "${NEEDED_MB}m" -nospotlight -ov "${WORKDIR}/staging.sparseimage"
        hdiutil attach "${WORKDIR}/staging.sparseimage" -nobrowse -noverify -noautoopen -owners on -mountpoint "$MOUNT_DIR"
        rsync -a "$SRC/" "$MOUNT_DIR/"
        sync
        hdiutil detach "$MOUNT_DIR"
        hdiutil convert "${WORKDIR}/staging.sparseimage" -format UDBZ -o "$OUT" -ov
        echo "[✓] DMG ready: $OUT"

    - name: Notarize with Apple NotaryTool
      shell: bash
      run: |
        echo "📦 Soumission à Apple NotaryTool..."
        xcrun notarytool submit "${{ inputs.dmg_path }}" \
          --apple-id "${{ inputs.apple_id }}" \
          --team-id "${{ inputs.team_id }}" \
          --password "${{ inputs.password }}" \
          --wait \
          --output-format json > notarytool-output.json

        status=$(jq -r '.status // empty' notarytool-output.json)
        submission_id=$(jq -r '.id // empty' notarytool-output.json)
        echo "🛡️ Statut notarisation: $status"

        if [[ "$status" == "Accepted" ]]; then
          echo "✅ Notarisation réussie"
          exit 0
        elif [[ "$status" == "Invalid" ]]; then
          echo "❌ Notarisation rejetée"
          xcrun notarytool log "$submission_id" \
            --apple-id "${{ inputs.apple_id }}" \
            --team-id "${{ inputs.team_id }}" \
            --password "${{ inputs.password }}" \
            --output-format normal || true
          exit 1
        else
          echo "❌ Statut inattendu: $status"
          exit 1
        fi