name: Codesign Product
description: Submit product to notary

inputs:
  sign:
    required: true
    type: string
  keychain:
    required: true
    type: string
  apple_id:
    required: true
    type: string 
  team_id:
    required: true
    type: string 
  password:
    required: true
    type: string 
  product_path:
    required: true
    type: string
  dmg_path:
    required: true
    type: string

outputs:
  product_path: 
    value: ${{ inputs.product_path }}
  dmg_path: 
    value: ${{ inputs.dmg_path }}
  notarization_status:
    value: ${{ steps.notarytool.outputs.notarization_status }}

runs:
  using: "composite"
  steps:

    - name: setup
      id: setup
      run: |
        echo "dmg_path=${{ inputs.dmg_path }}" >> $GITHUB_OUTPUT
        curl "${entitlements_url}" -o entitlements.plist -sL
        echo "entitlements_path=${GITHUB_WORKSPACE}/entitlements.plist" >> $GITHUB_OUTPUT
      shell: bash
      env:
        path: ${{ inputs.product_path }}
        entitlements_url: 'https://raw.githubusercontent.com/miyako/4D/v1/entitlements.plist'

    - name: Normalize ALL WebViewerCEF bundles (helpers exec must not be symlinks)
      shell: bash
      run: |
        set -euo pipefail
        shopt -s nullglob

        echo "🔎 Scan des répertoires *WebViewerCEF.bundle/Contents/Frameworks* dans ${GITHUB_WORKSPACE}"

        py_resolve='import os,sys; base=sys.argv[1]; tgt=sys.argv[2]; print(os.path.abspath(os.path.join(base, tgt)))'

        FOUND=0
        while IFS= read -r -d '' BUNDLE_ROOT; do
          FOUND=1
          echo "📦 Bundle: $BUNDLE_ROOT"

          SRC_CEF="${BUNDLE_ROOT}/Chromium Embedded Framework.framework"
          if [ ! -d "$SRC_CEF" ]; then
            echo "❌ CEF introuvable dans $BUNDLE_ROOT"; exit 1
          fi

          while IFS= read -r -d '' APP; do
            NAME="$(basename "$APP" .app)"
            EXE="$APP/Contents/MacOS/$NAME"

            # 1) L'exécutable principal ne doit pas être un symlink
            if [ -L "$EXE" ]; then
              TGT="$(readlink "$EXE")"
              RESOLVED=$(python3 -c "$py_resolve" "$(dirname "$EXE")" "$TGT")
              if [ ! -f "$RESOLVED" ]; then
                echo "❌ Cible du symlink introuvable: $EXE -> $TGT"; exit 1
              fi
              echo "🪄 Remplace symlink exécutable: $EXE  (-> $TGT)"
              rm -f "$EXE"
              /usr/bin/ditto "$RESOLVED" "$EXE"
              chmod 755 "$EXE"
            fi

            # 2) Chaque helper doit avoir sa copie locale du framework CEF
            DEST_CEF="$APP/Contents/Frameworks/Chromium Embedded Framework.framework"
            if [ -L "$DEST_CEF" ]; then
              echo "🪄 Supprime symlink CEF dans $APP"
              rm -f "$DEST_CEF"
            fi
            if [ ! -d "$DEST_CEF" ]; then
              echo "📚 Copie CEF local dans: $DEST_CEF"
              /usr/bin/ditto "$SRC_CEF" "$DEST_CEF"
            fi

          done < <(find "$BUNDLE_ROOT" -type d -name "4D Helper*.app" -print0)

        done < <(find "${GITHUB_WORKSPACE}" -type d -path "*/WebViewerCEF.bundle/Contents/Frameworks" -print0)

        if [ $FOUND -eq 0 ]; then
          echo "ℹ️ Aucun WebViewerCEF.bundle trouvé (ce n’est pas bloquant)"
        fi

    - name: Preflight — aucun exécutable de helper ne doit être un symlink
      shell: bash
      run: |
        set -euo pipefail
        SYMLINKS_FOUND=0

        while IFS= read -r -d '' SYM; do
          if [ $SYMLINKS_FOUND -eq 0 ]; then
            echo "❌ Symlinks d'exécutables trouvés :"
          fi
          echo " - $SYM"
          SYMLINKS_FOUND=1
        done < <(find "${GITHUB_WORKSPACE}" -type l -path "*/4D Helper*.app/Contents/MacOS/*" -print0)

        if [ $SYMLINKS_FOUND -eq 1 ]; then
          exit 1
        fi

        echo "✅ OK — aucun symlink executable dans les helpers"

    - name: Codesign
      shell: bash
      run: |
        set -euo pipefail

        sign_target() {
          local target="$1"
          echo "🔧 Signing: $target"
          codesign --verbose --strict --options=runtime --timestamp \
            --force --sign "${SIGN_IDENTITY}" --keychain "${KEYCHAIN}" \
            --entitlements "${ENTITLEMENTS}" "$target"
        }

        sign_bundle_recursively() {
          local bundle="$1"

          # 1️⃣ Signer tous les binaires exécutables et libs à l’intérieur
          find "$bundle" -type f \( -perm -111 -o -name "*.dylib" -o -name "*.so" \) -print0 | while IFS= read -r -d '' file; do
            sign_target "$file"
          done

          # 2️⃣ Signer les frameworks internes
          find "$bundle" -type d -name "*.framework" -print0 | while IFS= read -r -d '' fw; do
            fw_name=$(basename "$fw" .framework)
            # Binaire principal du framework
            fw_bin="$fw/Versions/Current/$fw_name"
            [ -f "$fw_bin" ] && sign_target "$fw_bin"

            # Tous les dylibs à l’intérieur
            find "$fw" -type f -name "*.dylib" -print0 | while IFS= read -r -d '' lib; do
              sign_target "$lib"
            done

            # Signer le framework lui-même
            sign_target "$fw"
          done

          # 3️⃣ Signer les bundles/plugins/kexts/apps internes
          find "$bundle" -type d \( -name "*.bundle" -o -name "*.plugin" -o -name "*.kext" -o -name "*.app" \) -mindepth 1 -print0 | while IFS= read -r -d '' sub; do
            sign_bundle_recursively "$sub"
          done

          # 4️⃣ Signer le bundle parent après tout ce qui est à l’intérieur
          sign_target "$bundle"
        }

        echo "=== Signing all main components (excluding .4dbase/.4darchive) ==="
        find "${PRODUCT_PATH}" \
          \( -type f -perm -111 -o -name "*.dylib" -o -name "*.so" \
            -o -type d -name "*.framework" -o -type d -name "*.bundle" -o -type d -name "*.plugin" -o -type d -name "*.kext" -o -type d -name "*.app" \) \
          ! -path "*.4dbase/*" ! -path "*.4darchive/*" -print0 | while IFS= read -r -d '' item; do
            sign_target "$item"
        done

        echo "=== Signing Native Components ==="
        for native_dir in "Native Components" "Components" "native_components" "components"; do
          native_path="${PRODUCT_PATH}/${native_dir}"
          if [ -d "$native_path" ]; then
            find "$native_path" -maxdepth 1 -type d \( -name "*.bundle" -o -name "*.plugin" -o -name "*.kext" -o -name "*.app" \) -print0 | while IFS= read -r -d '' bundle; do
              sign_bundle_recursively "$bundle"
            done
          fi
        done

        echo "=== Signing contents of .4darchive and .4dbase ==="
        find "${PRODUCT_PATH}" -type d \( -name "*.4dbase" -o -name "*.4darchive" \) -print0 | while IFS= read -r -d '' archive; do
          echo "📂 Signing archive: $archive"

          # Signer tous les binaires internes
          find "$archive" -type f \( -perm -111 -o -name "*.dylib" -o -name "*.so" \) -print0 | while IFS= read -r -d '' file; do
            sign_target "$file"
          done

          # Signer les frameworks internes
          find "$archive" -type d -name "*.framework" -print0 | while IFS= read -r -d '' fw; do
            fw_name=$(basename "$fw" .framework)
            fw_bin="$fw/Versions/Current/$fw_name"
            [ -f "$fw_bin" ] && sign_target "$fw_bin"

            find "$fw" -type f -name "*.dylib" -print0 | while IFS= read -r -d '' lib; do
              sign_target "$lib"
            done
            sign_target "$fw"
          done

          # Signer les apps internes
          find "$archive" -type d -name "*.app" -print0 | while IFS= read -r -d '' app; do
            mainexe="$app/Contents/MacOS/$(basename "$app" .app)"
            [ -f "$mainexe" ] && sign_target "$mainexe"

            find "$app" -type f -name "*.dylib" -print0 | while IFS= read -r -d '' dylib; do
              sign_target "$dylib"
            done

            sign_bundle_recursively "$app"
          done

          # Signer bundles/plugins/kexts internes
          find "$archive" -type d \( -name "*.bundle" -o -name "*.plugin" -o -name "*.kext" \) -print0 | while IFS= read -r -d '' bp; do
            sign_bundle_recursively "$bp"
          done

          # Signer Native Components internes à l’archive
          for native_dir in "Native Components" "Components" "native_components" "components"; do
            native_path="$archive/$native_dir"
            [ -d "$native_path" ] && find "$native_path" -maxdepth 1 -type d \( -name "*.bundle" -o -name "*.plugin" -o -name "*.kext" -o -name "*.app" \) -print0 | while IFS= read -r -d '' bundle; do
              sign_bundle_recursively "$bundle"
            done
          done
        done

        echo "=== Signing main app if applicable ==="
        if [[ "${PRODUCT_PATH}" == *.app ]]; then
          sign_bundle_recursively "${PRODUCT_PATH}"
        fi

      env:
        SIGN_IDENTITY: ${{ inputs.sign }}
        KEYCHAIN: ${{ inputs.keychain }}
        PRODUCT_PATH: ${{ inputs.product_path }}
        ENTITLEMENTS: ${{ steps.setup.outputs.entitlements_path }}

    - name: hdiutil (sparse -> convert)
      id: hdiutil
      if: ${{ !contains(inputs.product_path, 'update.mac.4darchive') }}
      shell: bash
      env:
        product_path: ${{ inputs.product_path }}
        dmg_path: ${{ steps.setup.outputs.dmg_path }}
        FS: HFS+                 # ou APFS si tu préfères
        FORMAT: UDBZ             # UDBZ (bzip2) ou UDZO (zlib)
        MARGIN_PCT: "50"         # marge % au-dessus de la taille source
        EXTRA_MB: "500"          # marge fixe supplémentaire en MB
        VERIFY: "1"              # 0 pour désactiver verify
      run: |
        set -euo pipefail

        SRC="${product_path}"
        OUT="${dmg_path}"
        VOLNAME="$(basename "${OUT%.dmg}")"
        WORKDIR="$(mktemp -d /tmp/dmgbuild.XXXXXX)"
        MOUNT_DIR="${WORKDIR}/mnt"
        mkdir -p "$MOUNT_DIR"

        # Estimation taille
        SRC_KB=$(du -sk "$SRC" | awk '{print $1}')
        SRC_MB=$(( SRC_KB / 1024 ))
        if [[ $SRC_MB -lt 1 ]]; then SRC_MB=1; fi
        NEEDED_MB=$(( SRC_MB + (SRC_MB * ${MARGIN_PCT} / 100) + ${EXTRA_MB} ))
        if [[ $NEEDED_MB -lt 300 ]]; then NEEDED_MB=300; fi

        # Sparse + montage
        hdiutil create -type SPARSE -fs "${FS}" -volname "${VOLNAME}" -nospotlight \
          -size "${NEEDED_MB}m" -ov "${WORKDIR}/staging.sparseimage"

        hdiutil attach "${WORKDIR}/staging.sparseimage" -nobrowse -noverify -noautoopen -owners on \
          -mountpoint "${MOUNT_DIR}"

        # Copie
        rsync -a --delete "${SRC}" "${MOUNT_DIR}/"

        # Démontage
        sync
        hdiutil detach "${MOUNT_DIR}" || hdiutil detach -force "${MOUNT_DIR}" || true

        # Compact + conversion
        hdiutil compact "${WORKDIR}/staging.sparseimage" || true
        hdiutil convert "${WORKDIR}/staging.sparseimage" -format "${FORMAT}" -o "${OUT}" -ov

        # Verify optionnel
        if [[ "${VERIFY}" == "1" ]]; then
          hdiutil verify "${OUT}"
        fi

        echo "[✓] DMG prêt: ${OUT}"

    - name: Debug notarization env vars
      id: debug-notarization
      if: ${{ !contains(inputs.product_path, 'update.mac.4darchive') }}
      run: |
        echo "Apple ID: ${apple_id}"
        echo "Team ID: ${team_id}"
        echo "Password is set: [${#password} characters]"
      shell: bash
      env:
        apple_id: ${{ inputs.apple_id }}
        team_id: ${{ inputs.team_id }}
        password: ${{ inputs.password }}

    - name: Notarize with Apple NotaryTool and check result (polling)
      id: notarytool
      if: ${{ !contains(inputs.product_path, 'update.mac.4darchive') }}
      shell: bash
      run: |
        set -euo pipefail

        echo "📦 Soumission à Apple NotaryTool..."
        json_output_file="notarytool-submit.json"
        status_file="${GITHUB_WORKSPACE}/notarization_status.txt"

        # soumission (sans --wait)
        xcrun notarytool submit "${dmg_path}" \
          --apple-id "${apple_id}" \
          --team-id "${team_id}" \
          --password "${password}" \
          --output-format json >"$json_output_file"

        echo "📄 JSON submit:"
        cat "$json_output_file" || true

        submission_id=$(jq -r '.id // empty' "$json_output_file")
        if [[ -z "$submission_id" ]]; then
          echo "❌ Impossible de récupérer l’ID de soumission"
          exit 1
        fi
        echo "🆔 Soumission envoyée, ID=$submission_id"

        # Polling (10s) jusqu'à 1h (360 tentatives)
        attempt=0
        max_attempts=360
        status="In Progress"
        while [[ "$status" == "In Progress" && $attempt -lt $max_attempts ]]; do
          sleep 10
          attempt=$((attempt+1))
          echo "⏳ Vérification notarisation (tentative $attempt)..."
          out=$(xcrun notarytool info "$submission_id" \
            --apple-id "${apple_id}" \
            --team-id "${team_id}" \
            --password "${password}" \
            --output-format json 2>/dev/null || true)
          status=$(echo "$out" | jq -r '.status // empty')
          echo "Statut actuel: ${status:-unknown}"

          # Optionnel: écrire l’instantané JSON pour debug
          echo "$out" > "notarytool-info-$attempt.json" || true
        done

        echo "${status:-Unknown}" > "$status_file"
        echo "notarization_status=${status:-Unknown}" >> $GITHUB_OUTPUT

        if [[ "$status" == "Accepted" ]]; then
          echo "✅ Notarisation réussie"
          exit 0
        elif [[ "$status" == "Invalid" ]]; then
          echo "❌ Notarisation rejetée (Invalid)"
          xcrun notarytool log "$submission_id" \
            --apple-id "${apple_id}" \
            --team-id "${team_id}" \
            --password "${password}" \
            --output-format json || true
          exit 1
        else
          echo "❌ Notarisation non terminée ou statut inattendu: '${status:-Unknown}'"
          exit 1
        fi
      env:
        apple_id: ${{ inputs.apple_id }}
        team_id: ${{ inputs.team_id }}
        password: ${{ inputs.password }}
        dmg_path: ${{ steps.setup.outputs.dmg_path }}
