name: Codesign & Notarize Product
description: Sign, package and submit product to Apple Notary

inputs:
  sign:
    required: true
    type: string
  keychain:
    required: true
    type: string
  apple_id:
    required: true
    type: string 
  team_id:
    required: true
    type: string 
  password:
    required: true
    type: string 
  product_path:
    required: true
    type: string
  dmg_path:
    required: true
    type: string

outputs:
  product_path: 
    value: ${{ inputs.product_path }}
  dmg_path: 
    value: ${{ inputs.dmg_path }}
  notarization_status:
    value: ${{ steps.notarytool.outputs.notarization_status }}

runs:
  using: "composite"
  steps:

    - name: Setup
      id: setup
      shell: bash
      run: |
        echo "dmg_path=${{ inputs.dmg_path }}" >> $GITHUB_OUTPUT
        curl -sL "${ENTITLEMENTS_URL}" -o entitlements.plist
        echo "entitlements_path=${GITHUB_WORKSPACE}/entitlements.plist" >> $GITHUB_OUTPUT
      env:
        ENTITLEMENTS_URL: 'https://raw.githubusercontent.com/miyako/4D/v1/entitlements.plist'

    - name: Codesign
      shell: bash
      env:
        sign: ${{ inputs.sign }}
        keychain: ${{ inputs.keychain }}
        product_path: ${{ inputs.product_path }}
        entitlements_path: ${{ steps.setup.outputs.entitlements_path }}
      run: |
        set -euo pipefail

        retry_codesign() {
          local target="$1"
          local attempt=1
          local max_attempts=3
          local delay=5
          
          if [ ! -e "$target" ]; then
            echo "⚠️ Ignoring non-existent target: $target"
            return 0
          fi

          while [ $attempt -le $max_attempts ]; do
            echo "[$attempt/$max_attempts] codesign: $target"
            if codesign --verbose --deep --strict --options=runtime --timestamp \
              --force --sign "${sign}" --keychain "${keychain}" --entitlements "${entitlements_path}" "$target"; then
              echo "✅ codesign réussi pour $target"
              return 0
            fi
            echo "⚠️ Tentative $attempt échouée, retry dans ${delay}s..."
            sleep $delay
            attempt=$(( attempt + 1 ))
            delay=$(( delay * 2 ))
          done

          echo "❌ Échec après $max_attempts tentatives pour $target"
          return 1
        }

        echo "[i] Collecting valid Mach-O and bundle items..."
        # Liste des items valides
        VALID_ITEMS=()
        while IFS= read -r -d '' item; do
          if file "$item" | grep -qE 'Mach-O|bundle'; then
            VALID_ITEMS+=("$item")
          fi
        done < <(find "${product_path}" -type f -or -type d -print0)

        echo "[i] Found ${#VALID_ITEMS[@]} valid items to sign."

        # Sign items en parallèle avec xargs
        printf "%s\0" "${VALID_ITEMS[@]}" | xargs -0 -n1 -P4 bash -c 'retry_codesign "$0"' || exit 1

        echo "✅ Tous les composants valides signés."

    - name: Create DMG
      id: hdiutil
      shell: bash
      env:
        product_path: ${{ inputs.product_path }}
        dmg_path: ${{ steps.setup.outputs.dmg_path }}
      run: |
        set -euo pipefail
        SRC="${product_path}"
        OUT="${dmg_path}"
        VOLNAME="$(basename "${OUT%.dmg}")"
        WORKDIR="$(mktemp -d /tmp/dmgbuild.XXXXXX)"
        MOUNT_DIR="${WORKDIR}/mnt"
        mkdir -p "$MOUNT_DIR"

        echo "[i] Creating sparse image..."
        SRC_MB=$(( $(du -sm "$SRC" | cut -f1) ))
        NEEDED_MB=$(( SRC_MB * 2 ))
        hdiutil create -type SPARSE -fs HFS+ -volname "$VOLNAME" -size "${NEEDED_MB}m" -nospotlight -ov "${WORKDIR}/staging.sparseimage"
        hdiutil attach "${WORKDIR}/staging.sparseimage" -nobrowse -noverify -noautoopen -owners on -mountpoint "$MOUNT_DIR"
        rsync -a "$SRC/" "$MOUNT_DIR/"
        sync
        hdiutil detach "$MOUNT_DIR"
        hdiutil convert "${WORKDIR}/staging.sparseimage" -format UDBZ -o "$OUT" -ov
        echo "[✓] DMG ready: $OUT"

    - name: Notarize with Apple NotaryTool
      id: notarytool
      shell: bash
      env:
        dmg_path: ${{ steps.setup.outputs.dmg_path }}
        apple_id: ${{ inputs.apple_id }}
        team_id: ${{ inputs.team_id }}
        password: ${{ inputs.password }}
      run: |
        set -euo pipefail
        max_attempts=3
        attempt=1
        delay=30

        while [ $attempt -le $max_attempts ]; do
          echo "📦 Submission to Apple NotaryTool, attempt $attempt..."
          if xcrun notarytool submit "${dmg_path}" \
            --apple-id "${apple_id}" \
            --team-id "${team_id}" \
            --password "${password}" \
            --wait \
            --output-format json > notarytool-output.json; then
              
              status=$(jq -r '.status // empty' notarytool-output.json)
              submission_id=$(jq -r '.id // empty' notarytool-output.json)
              echo "🛡️ Notarization status: $status"
              
              if [[ "$status" == "Accepted" ]]; then
                echo "✅ Notarization succeeded"
                break
              elif [[ "$status" == "Invalid" ]]; then
                echo "❌ Notarization rejected"
                xcrun notarytool log "$submission_id" \
                  --apple-id "${apple_id}" \
                  --team-id "${team_id}" \
                  --password "${password}" \
                  --output-format normal || true
                exit 1
              else
                echo "⚠️ Unexpected status: $status"
              fi
          else
            echo "⚠️ Submission failed, retrying in $delay seconds..."
          fi
          sleep $delay
          attempt=$(( attempt + 1 ))
          delay=$(( delay * 2 ))
        done

        if [[ "$status" != "Accepted" ]]; then
          echo "❌ Notarization ultimately failed after $max_attempts attempts."
          exit 1
        fi

        echo "✅ Notarization completed successfully"