name: "build create packagejson"
description: "if the file package.json doesn't exist then it is being created with the name in the inputs"

inputs:
  name:
    description: "name of the project"
    required: true
    default: "Unknown"
  version:
    description: "initial version of the project"
    required: true
    default: "0.0.0"

runs:
  using: "composite"
  steps:

    - name: git config 
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"  
      shell: bash

    - name: Create package.json
      id: create_packagejson
      shell: bash
      run: |
        if [ ! -f package.json ]; then
          echo "{\"name\": \"${{ inputs.name }}\",\"version\": \"${{ inputs.version }}\",\"description\": \"\",\"main\": \"index.js\",\"type\": \"module\",\"scripts\": {\"release:major\": \"release-it major\",\"release:minor\": \"release-it minor\",\"release:patch\": \"release-it patch\"},\"devDependencies\": {\"dotenv\": \"^16.0.3\",\"form-data\": \"^4.0.0\",\"node-fetch\": \"^3.3.2\",\"release-it\": \"^15.10.1\"},\"engines\": {\"4d\": \">=20.2.0\"},\"keywords\": [],\"author\": \"\",\"license\": \"ISC\",\"dependencies\": {\"commander\": \"^11.0.0\"}}" > package.json
          echo "package.json created."
          git config --global commit.gpgsign false
          git add package.json
          git commit -m "Create package.json"
          git push origin
        else
          echo "package.json already exists."
        fi
        echo "package_json_exists=$(test -f package.json && echo true || echo false)" >> $GITHUB_OUTPUT
