name: Set Package Version
description: Write updated version code to package.json

inputs:
  mode: 
    required: true
    type: string

outputs:
  version:
    value: ${{ steps.set.outputs.version }}
  mode:
    value: ${{ inputs.mode }}

runs:
  using: "composite"
  steps:

    - name: Configure Git
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
      shell: bash

    - name: Pull latest changes
      run: git pull origin main
      shell: bash

    - name: Fetch remote tags
      run: git fetch --tags
      shell: bash

    - name: Handle version bump
      run: |
        # Détection du mode
        MODE="${{ inputs.mode }}"

        # Calcule la prochaine version avec npm dry-run
        NEXT_VERSION=$(npm version "$MODE" --dry-run | grep -oP 'v?\d+\.\d+\.\d+' | tail -n1)
        TAG="v$NEXT_VERSION"

        echo "Tentative de version bump: $MODE → $NEXT_VERSION ($TAG)"

        # Si le tag existe localement
        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "Tag $TAG existe en local."
          # Et s’il n’existe PAS à distance → suppression
          if ! git ls-remote --tags origin | grep -q "refs/tags/$TAG"; then
            echo "Tag $TAG n'existe pas à distance → suppression locale."
            git tag -d "$TAG"
          else
            echo "❌ Tag $TAG existe déjà à distance → abandon."
            exit 1
          fi
        fi

        # Exécute le bump réel et crée le tag
        npm version "$MODE"

        echo "✔️ Version bump réussi vers $NEXT_VERSION"
      shell: bash

    - name: Push commit and tag
      run: git push origin main --follow-tags
      shell: bash

    - id: set
      run: |
        version=$(jq -r '.version' package.json)
        echo "version=${version}" >> "$GITHUB_OUTPUT"
      shell: bash